### ISSUE TITLE
KontoauszugPdf nicht in HBCIBatch unterstützt

### ISSUE THREAD

**Issue by Deltachaos** [hbci4j/hbci4java#22]
Der GV KontoauszugPdf scheint aktuell nicht in HBCIBatch unterstützt zu sein, zumindest bekomme ich immer die Fehlermeldung:

```
Exception in thread "main" org.kapott.hbci.exceptions.HBCI_Exception: Fehler beim Erzeugen des Jobs KontoauszugPdf
        at org.kapott.hbci.manager.HBCIHandler.newJob(HBCIHandler.java:388)
        at org.kapott.hbci.tools.HBCIBatch.main(HBCIBatch.java:312)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.kapott.hbci.manager.HBCIHandler.newJob(HBCIHandler.java:382)
        ... 1 more
Caused by: org.kapott.hbci.exceptions.JobNotSupportedException: Geschäftsvorfall KontoauszugPdf wird nicht unterstützt, evtl. andere HBCI-Version benutzen
        at org.kapott.hbci.GV.HBCIJobImpl.findSpecNameForGV(HBCIJobImpl.java:227)
        at org.kapott.hbci.GV.HBCIJobImpl.<init>(HBCIJobImpl.java:96)
        at org.kapott.hbci.GV.GVKontoauszugPdf.<init>(GVKontoauszugPdf.java:45)
        at org.kapott.hbci.GV.GVKontoauszugPdf.<init>(GVKontoauszugPdf.java:54)
        ... 6 more
```

An der Version kann es nicht liegen, die steht auf 300. So wie ich gesehen habe wird KontoauszugPdf auch in Version 300 unterstützt.

**Comment by willuhn** [comment]
HBCIBatch kennt gar keine spezifischen Geschaeftsvorfaelle. Von daher kann es nicht einen Geschaeftsvorfall unterstuetzen und einen anderen nicht. Der Grund ist einfach, dass deine Bank den Abruf von elektronischen Kontoauszuegen im PDF-Format laut BPD gar nicht per FinTS unterstützt.

**Comment by Deltachaos** [comment]
Interessanterweise funktioniert der Abruf über MoneyMoney jedoch auch mit dem Geschäftsvorfall HKEKP. Also müsste die Bank das dann doch unterstützen? Wenn ich `client.errors.ignoreJobNotSupported` auf `yes` Stelle bekomme ich eine NullPointerException.

``
<ERR> [2019.03.04 08:33:10.821] [main/main] manager.HBCIUtilsInternal: Geschäftsvorfall KontoauszugPdf wird nicht unterstützt, evtl. andere HBCI-Version benutzen
<ERR> [2019.03.04 08:33:10.855] [main/main] manager.HBCIUtilsInternal: ignoring error because param client.errors.ignoreJobNotSupported=yes
<WRN> [2019.03.04 08:33:10.855] [main/main] GV.HBCIJobImpl: Using segment version 1 for job KontoauszugPdf, although not found in BPD. This may fail
Exception in thread "main" org.kapott.hbci.exceptions.HBCI_Exception: Fehler beim Hinzufügen des Auftrages KontoauszugPdf1 zum aktuellen Dialog
        at org.kapott.hbci.manager.HBCIDialog.addTask(HBCIDialog.java:520)
        at org.kapott.hbci.manager.HBCIHandler.addJobToDialog(HBCIHandler.java:424)
        at org.kapott.hbci.GV.HBCIJobImpl.addToQueue(HBCIJobImpl.java:1137)
        at org.kapott.hbci.tools.HBCIBatch.main(HBCIBatch.java:393)
Caused by: java.lang.NullPointerException
        at org.kapott.hbci.GV.HBCIJobImpl.getHBCICode(HBCIJobImpl.java:160)
        at org.kapott.hbci.manager.HBCIDialog.addTask(HBCIDialog.java:472)
        ... 3 more
``

**Comment by willuhn** [comment]
Der Nullpointer ist ein Folgefehler. Mit dem Parameter hast du unterdrueckt, dass HBCI4Java die Ausfuehrung verweigert, wenn der GV laut BPD nicht unterstuetzt wird. Anschliessend kann HBCI4Java die Eckdaten des GV nicht in den BPD finden.

Fuer den Abruf von eleketronischen Kontoauszuegen gibt es zwei Geschaeftsvorfaelle. HKEKP ausschliesslich im PDF-Format und HKEKA - dort ist MT940 und PDF moeglich. Die Bank entscheidet da selbst, welche Dateiformate sie anbietet. Wahrscheinlich unterstuetzt die Bank den Abruf nur per HKEKA. In HBCI4Java waere das dann "Kontoauszug" statt "KontoauszugPdf". Du kannst den Bankzugang ja zum Vergleich auch mal in Hibiscus einrichten - dort werden beide GVs unterstuetzt und Hibiscus waehlt selbst den jeweils von der Bank unterstuetzten aus. Siehe https://www.willuhn.de/wiki/doku.php?id=handbuch:kontoauszug

Um welche Bank handelt es sich denn ueberhaupt?
