### ISSUE TITLE
Unable to connect to ING (50010517) (Fehler beim Ermitteln einer neuen System-ID 

### ISSUE THREAD

**Issue by jhmgbl** [hbci4j/hbci4java#25]
Here is the log:
1:12:36:32:No supported passport formats found

1:12:37:38:no supported legacy converters found

1:12:39:33:Meldung der Bank: 9800:Der Dialog wurde abgebrochen.

1:12:39:33:Meldung der Bank: 9400:Der anonyme Dialog wird nicht unterstützt.

1:12:39:36:Meldung der Bank: 9800:Der Dialog wurde abgebrochen.

1:12:39:36:Meldung der Bank: 9110:Unbekannter Aufbau der Kundennachricht.

1:12:39:36:org.kapott.hbci.exceptions.HBCI_Exception: empfangene Nachrichtennummer (9999) im Nachrichtenkopf entspricht nicht der gesendeten Nachrichtennummer (2)
	at org.kapott.hbci.manager.HBCIKernelImpl.rawDoIt(HBCIKernelImpl.java:428)
	at org.kapott.hbci.manager.HBCIKernelImpl.rawDoIt(HBCIKernelImpl.java:176)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.sendData(AbstractRawHBCIDialog.java:103)
	at org.kapott.hbci.dialog.HBCIDialogEnd.sendData(HBCIDialogEnd.java:84)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.execute(AbstractRawHBCIDialog.java:76)
	at org.kapott.hbci.manager.HBCIInstitute.fetchBPD(HBCIInstitute.java:283)
	at org.kapott.hbci.manager.HBCIInstitute.register(HBCIInstitute.java:372)
	at org.kapott.hbci.manager.HBCIHandler.registerInstitute(HBCIHandler.java:267)
	at org.kapott.hbci.manager.HBCIHandler.<init>(HBCIHandler.java:132)
	at org.de.jmg.hbci4android2.Banking.getAccounts(Banking.java:188)
	at org.de.jmg.hbci4android2.HBCIAdapter$8.doInBackground(HBCIAdapter.java:844)
	at org.de.jmg.hbci4android2.HBCIAdapter$8.doInBackground(HBCIAdapter.java:835)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2:12:39:36:dialog end failed: org.kapott.hbci.exceptions.HBCI_Exception: empfangene Nachrichtennummer (9999) im Nachrichtenkopf entspricht nicht der gesendeten Nachrichtennummer (2)
9800:Der Dialog wurde abgebrochen.
9110:Unbekannter Aufbau der Kundennachricht.

1:12:39:37:org.kapott.hbci.exceptions.ProcessException: Dialog-Ende fehlgeschlagen
	at org.kapott.hbci.dialog.HBCIDialogEnd.checkResult(HBCIDialogEnd.java:113)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.execute(AbstractRawHBCIDialog.java:86)
	at org.kapott.hbci.manager.HBCIInstitute.fetchBPD(HBCIInstitute.java:283)
	at org.kapott.hbci.manager.HBCIInstitute.register(HBCIInstitute.java:372)
	at org.kapott.hbci.manager.HBCIHandler.registerInstitute(HBCIHandler.java:267)
	at org.kapott.hbci.manager.HBCIHandler.<init>(HBCIHandler.java:132)
	at org.de.jmg.hbci4android2.Banking.getAccounts(Banking.java:188)
	at org.de.jmg.hbci4android2.HBCIAdapter$8.doInBackground(HBCIAdapter.java:844)
	at org.de.jmg.hbci4android2.HBCIAdapter$8.doInBackground(HBCIAdapter.java:835)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

1:12:39:37:fetching BPD failed: 9800:Der Dialog wurde abgebrochen.
9400:Der anonyme Dialog wird nicht unterstützt.

2:12:39:37:can not check if requested parameters are supported

2:12:39:41:the job with the code HNSHK seems not to be allowed with PIN/TAN

2:12:39:41:the job with the code HKIDN seems not to be allowed with PIN/TAN

2:12:39:41:the job with the code HKVVB seems not to be allowed with PIN/TAN

2:12:39:41:the job with the code HKTAN seems not to be allowed with PIN/TAN

2:12:39:41:the job with the code HKSYN seems not to be allowed with PIN/TAN

1:12:39:50:Meldung der Bank: 9050:Nachricht teilweise fehlerhaft.

1:12:39:50:Meldung der Bank: 9010:Der gewünschte Geschäftsvorfall wird nicht unterstützt. (5: Synch.TAN2Step6)

2:12:39:50:message has no signature

**Comment by willuhn** [comment]
Unter https://github.com/hbci4j/hbci4java/issues/24 hast du doch hierzu schon ein Ticket angelegt.
Wie gesagt: Die ING unterstützt PSD2 scheinbar noch nicht. Verwende bis auf weiteres die älteren 3.0.x Versionen von HBCI4Java. Wenn die ING dann tatsächlich auf PSD2 umstellt, könnte u.U. zumindest der Umsatzabruf wieder funktioneren. 

Das Problem ist hier aber wie gesagt die ING, die es nicht schafft, ihre FinTS-Server ordentlich PSD2-konform zu machen. Siehe https://www.willuhn.de/wiki/doku.php?id=psd2#die_ing_schrieb_mir_mein_banking-programm_soll_die_psd2-api_verwenden
