### ISSUE TITLE
Selected pintan method not supported

### ISSUE THREAD

**Issue by Krysztokowski** [hbci4j/hbci4java#27]
Nachdem ich heute versucht habe mein Projekt von der HBCI4J-Version 3.0.24 (PSD2-Fehler) auf die 3.1.13 zu updaten, erhalte ich beim Versuch meine Umsätze durch die Klasse UmsatzAbrufPinTan abzurufen, folgende Fehlermeldung:

`Exception in thread "main" org.kapott.hbci.exceptions.HBCI_Exception: Fehler beim Erzeugen eines HBCIHandler Objektes
	at org.kapott.hbci.manager.HBCIHandler.<init>(HBCIHandler.java:145)
	at hbci4j.test.App.main(App.java:103)
Caused by: org.kapott.hbci.exceptions.HBCI_Exception: Fehler beim Registrieren der Institutsdaten 
	at org.kapott.hbci.manager.HBCIHandler.registerInstitute(HBCIHandler.java:250)
	at org.kapott.hbci.manager.HBCIHandler.<init>(HBCIHandler.java:132)
	... 1 more
Caused by: org.kapott.hbci.exceptions.InvalidUserDataException: *** selected pintan method not supported: 
	at org.kapott.hbci.passport.AbstractPinTanPassport.chooseTANMethod(AbstractPinTanPassport.java:858)
	at org.kapott.hbci.passport.AbstractPinTanPassport.getCurrentTANMethod(AbstractPinTanPassport.java:822)
	at org.kapott.hbci.passport.AbstractPinTanPassport.isSupported(AbstractPinTanPassport.java:628)
	at org.kapott.hbci.manager.HBCIInstitute.fetchBPD(HBCIInstitute.java:314)
	at org.kapott.hbci.manager.HBCIInstitute.register(HBCIInstitute.java:372)
	at org.kapott.hbci.manager.HBCIHandler.registerInstitute(HBCIHandler.java:248)
	... 2 more
`

Ist die Demoklasse nach PSD2-Einführung deprecated oder mache ich etwas anderes falsch?
Scheint als hätte die Bank PSD2 erfolgreich integriert, aber auch wieder nicht, seltsam.

**Comment by willuhn** [comment]
Die ist nicht deprecated. Aber scheinbar hast du in deinem Programm ein TAN-Verfahren fest hinterlegt, welches so von deiner Bank nicht mehr unterstuetzt wird. Stelle sicher, dass du den Callback HBCICallback.NEED_PT_SECMECH mit einem TAN-Verfahren beantwortest, welches auch in de uebergebenen Liste enthalten ist. Du musst schon auch die Werte pruefen, die in dem Callback zur Auswahl angeboten werden und nicht pauschal ein gespeichertes verwenden.
