### ISSUE TITLE
org.kapott.hbci.exceptions.ParseErrorException: Fehler beim Erzeugen eines Syntax-DEs für DialogInitRes.MsgHead.SegHead.code

### ISSUE THREAD

**Issue by thimo-seitz** [hbci4j/hbci4java#55]
Beim Ausführen eines `GVSaldoReq` meldet die Bibliothek mir den Fehler `org.kapott.hbci.exceptions.ParseErrorException: Fehler beim Erzeugen eines Syntax-DEs für DialogInitRes.MsgHead.SegHead.code`. 
Die ursächliche Exception dafür ist eine `InvalidArgumentException`, mit der Message `Länge von  (0) muss zwischen 1 und 6 liegen`.

Ein Sonderfall, oder passt die Message von der Commerzbank nicht zur Definition?

**Comment by willuhn** [comment]
Die Meldung "Länge von (0) muss zwischen 1 und 6 liegen" besagt, dass da ein Feld, welches zwischen 1 und 6 Zeichen lang sein muss, von dir nicht belegt wurde. Vermutlich hast du bei der Erstellung des GV irgendwelche Daten nicht mit angegeben. GVSaldoReq ist eigentlich der GV, der immer funktioniert. Auch bei der Commerzbank. Mir sind hier auch keine Fehler von anderen Usern bekannt.

Prüfe daher mal bitte deinen Code. Wenn es nicht hilft, poste mal den relevanten Code-Ausschnitt und das Log. Mit der oben genannten Meldung kann man nur spekulieren.

**Comment by thimo-seitz** [comment]
Das ist aus dem Beispiel `https://github.com/hbci4j/hbci4java/blob/master/src/main/java/org/kapott/hbci/examples/UmsatzAbrufPinTan.java` nur eben umgestellt auf Schlüsseldatei. Bis vor einem Jahr ging's auch wunderbar. Die Umsätze dagegen werden auch abgefragt. Das Saldo hat als Parameter doch nur das Konto aus dem Passport, oder übersehe ich da was?

**Comment by thimo-seitz** [comment]
Hab das Konto in Hibiscus eingerichet. Dort gibt es dieselbe `ParseErrorException`. IBAN habe ich ge-X-t.

```
[09.03.2021 12:11:07] Synchronisierung via FinTS/HBCI läuft
[09.03.2021 12:11:07]  
[09.03.2021 12:11:07] Synchronisiere Konto: Kontokorrent, IBAN DEXXXXXXX [Commerzbank...sdner Bank]
[09.03.2021 12:11:07] Initialisiere Bank-Zugang
[09.03.2021 12:11:07]     Aktualisiere Bankparameter (BPD)
[09.03.2021 12:11:07]     Warte auf Antwortdaten
[09.03.2021 12:11:07] Aktualisiere BPD
[09.03.2021 12:11:07]   Kennung 1 - BPD-Parameter neu: 0, geändert: 0, gelöscht: 0
[09.03.2021 12:11:07]     Warte auf Antwortdaten
[09.03.2021 12:11:07]     Aktualisiere Benutzerparameter (UPD)
[09.03.2021 12:11:07]     Warte auf Antwortdaten
[09.03.2021 12:11:07]     Benutzerparameter (UPD) aktualisiert [Bisherige Version: 0, neue Version: 8]
[09.03.2021 12:11:07] Aktualisiere UPD
[09.03.2021 12:11:07]   Kennung 1 - UPD-Parameter neu: 0, geändert: 0, gelöscht: 0
[09.03.2021 12:11:07] Aktualisiere BPD
[09.03.2021 12:11:07]   Kennung 1 - BPD-Parameter neu: 0, geändert: 0, gelöscht: 0
[09.03.2021 12:11:07]     Warte auf Antwortdaten
[09.03.2021 12:11:08]     trying to fetch SEPA infos
[09.03.2021 12:11:08]     Warte auf Antwortdaten
[09.03.2021 12:11:08]     Warte auf Antwortdaten
[09.03.2021 12:11:08]     IBAN/BIC für 1 Konto empfangen
[09.03.2021 12:11:09]     Warte auf Antwortdaten
[09.03.2021 12:11:09] Führe Geschäftsvorfall aus: "Kontokorrent, IBAN DEXXXXXXX [Commerzbank...sdner Bank]: Salden abrufen"
[09.03.2021 12:11:09] Führe Aufträge aus...
[09.03.2021 12:11:09]     Führe Dialog-Initialisierung aus
[09.03.2021 12:11:09]     Warte auf Antwortdaten
[09.03.2021 12:11:09]     unable to apply rewriter RInvalidSuppHBCIVersion - leaving message unchanged: reststring in DialogInitRes.MsgHead: 
[09.03.2021 12:11:09]     unable to apply rewriter RSecTypeTAN - leaving message unchanged: reststring in DialogInitRes.MsgHead: 
[09.03.2021 12:11:09]     [Fehler] org.kapott.hbci.exceptions.CanNotParseMessageException: 
	at org.kapott.hbci.comm.Comm.pingpong(Comm.java:124)
	at org.kapott.hbci.manager.HBCIKernelImpl.rawDoIt(HBCIKernelImpl.java:348)
	at org.kapott.hbci.manager.HBCIKernelImpl.rawDoIt(HBCIKernelImpl.java:176)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.sendData(AbstractRawHBCIDialog.java:123)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.execute(AbstractRawHBCIDialog.java:96)
	at org.kapott.hbci.manager.HBCIDialog.doDialogInit(HBCIDialog.java:116)
	at org.kapott.hbci.manager.HBCIDialog.doIt(HBCIDialog.java:445)
	at org.kapott.hbci.manager.HBCIHandler.execute(HBCIHandler.java:416)
	at de.willuhn.jameica.hbci.synchronize.hbci.HBCISynchronizeBackend$HBCIJobGroup.executeJobs(HBCISynchronizeBackend.java:371)
	at de.willuhn.jameica.hbci.synchronize.hbci.HBCISynchronizeBackend$HBCIJobGroup.sync(HBCISynchronizeBackend.java:292)
	at de.willuhn.jameica.hbci.synchronize.AbstractSynchronizeBackend$Worker.run(AbstractSynchronizeBackend.java:407)
	at de.willuhn.jameica.gui.GUI$7.run(GUI.java:1081)
Caused by: org.kapott.hbci.exceptions.ParseErrorException: reststring in DialogInitRes.MsgHead: 
	at org.kapott.hbci.protocol.MultipleSyntaxElements.initData(MultipleSyntaxElements.java:476)
	at org.kapott.hbci.protocol.MultipleSyntaxElements.init(MultipleSyntaxElements.java:539)
	at org.kapott.hbci.protocol.MultipleSEGs.init(MultipleSEGs.java:76)
	at org.kapott.hbci.protocol.factory.MultipleSEGsFactory.createMultipleSEGs(MultipleSEGsFactory.java:61)
	at org.kapott.hbci.protocol.MSG.parseNewChildContainer(MSG.java:187)
	at org.kapott.hbci.protocol.SyntaxElement.parseAndAppendNewChildContainer(SyntaxElement.java:457)
	at org.kapott.hbci.protocol.SyntaxElement.initData(SyntaxElement.java:388)
	at org.kapott.hbci.protocol.SyntaxElement.init(SyntaxElement.java:452)
	at org.kapott.hbci.protocol.MSG.init(MSG.java:171)
	at org.kapott.hbci.protocol.factory.MSGFactory.createMSG(MSGFactory.java:92)
	at org.kapott.hbci.protocol.factory.MSGFactory.createMSG(MSGFactory.java:78)
	at org.kapott.hbci.protocol.factory.MSGFactory.createMSG(MSGFactory.java:73)
	at org.kapott.hbci.comm.Comm.pingpong(Comm.java:121)
	... 11 more
Caused by: org.kapott.hbci.exceptions.ParseErrorException: reststring in DialogInitRes.MsgHead.SegHead: 
	at org.kapott.hbci.protocol.MultipleSyntaxElements.initData(MultipleSyntaxElements.java:476)
	at org.kapott.hbci.protocol.MultipleSyntaxElements.init(MultipleSyntaxElements.java:539)
	at org.kapott.hbci.protocol.MultipleDEGs.init(MultipleDEGs.java:104)
	at org.kapott.hbci.protocol.factory.MultipleDEGsFactory.createMultipleDEGs(MultipleDEGsFactory.java:61)
	at org.kapott.hbci.protocol.SEG.parseNewChildContainer(SEG.java:140)
	at org.kapott.hbci.protocol.SyntaxElement.parseAndAppendNewChildContainer(SyntaxElement.java:457)
	at org.kapott.hbci.protocol.SyntaxElement.initData(SyntaxElement.java:388)
	at org.kapott.hbci.protocol.SyntaxElement.init(SyntaxElement.java:452)
	at org.kapott.hbci.protocol.SEG.init(SEG.java:159)
	at org.kapott.hbci.protocol.factory.SEGFactory.createSEG(SEGFactory.java:60)
	at org.kapott.hbci.protocol.MultipleSEGs.parseAndAppendNewElement(MultipleSEGs.java:82)
	at org.kapott.hbci.protocol.MultipleSyntaxElements.initData(MultipleSyntaxElements.java:396)
	... 23 more
Caused by: org.kapott.hbci.exceptions.ParseErrorException: reststring in DialogInitRes.MsgHead.SegHead.code: 
	at org.kapott.hbci.protocol.MultipleSyntaxElements.initData(MultipleSyntaxElements.java:476)
	at org.kapott.hbci.protocol.MultipleSyntaxElements.init(MultipleSyntaxElements.java:539)
	at org.kapott.hbci.protocol.MultipleDEs.init(MultipleDEs.java:146)
	at org.kapott.hbci.protocol.factory.MultipleDEsFactory.createMultipleDEs(MultipleDEsFactory.java:61)
	at org.kapott.hbci.protocol.DEG.parseNewChildContainer(DEG.java:110)
	at org.kapott.hbci.protocol.SyntaxElement.parseAndAppendNewChildContainer(SyntaxElement.java:457)
	at org.kapott.hbci.protocol.SyntaxElement.initData(SyntaxElement.java:388)
	at org.kapott.hbci.protocol.SyntaxElement.init(SyntaxElement.java:452)
	at org.kapott.hbci.protocol.DEG.init(DEG.java:127)
	at org.kapott.hbci.protocol.factory.DEGFactory.createDEG(DEGFactory.java:60)
	at org.kapott.hbci.protocol.MultipleDEGs.parseAndAppendNewElement(MultipleDEGs.java:87)
	at org.kapott.hbci.protocol.MultipleSyntaxElements.initData(MultipleSyntaxElements.java:396)
	... 34 more
Caused by: org.kapott.hbci.exceptions.ParseErrorException: Fehler beim Erzeugen eines Syntax-DEs für DialogInitRes.MsgHead.SegHead.code
	at org.kapott.hbci.datatypes.factory.SyntaxDEFactory.createSyntaxDE(SyntaxDEFactory.java:166)
	at org.kapott.hbci.protocol.DE.parseValue(DE.java:222)
	at org.kapott.hbci.protocol.DE.initData(DE.java:279)
	at org.kapott.hbci.protocol.DE.init(DE.java:296)
	at org.kapott.hbci.protocol.factory.DEFactory.createDE(DEFactory.java:61)
	at org.kapott.hbci.protocol.MultipleDEs.parseAndAppendNewElement(MultipleDEs.java:128)
	at org.kapott.hbci.protocol.MultipleSyntaxElements.initData(MultipleSyntaxElements.java:396)
	... 45 more
[09.03.2021 12:11:09] Aufträge ausgeführt
[09.03.2021 12:11:09] Fehler beim Abrufen das Saldos: Unbekannter Fehler
[09.03.2021 12:11:09] Umsatzabruf fehlgeschlagen: Unbekannter Fehler
[09.03.2021 12:11:09] Es sind Fehler aufgetreten
[09.03.2021 12:11:09] 
[09.03.2021 12:11:09] *****************************************************
[09.03.2021 12:11:09] Zusammengefasste Fehlermeldungen:
[09.03.2021 12:11:09]    org.kapott.hbci.exceptions.CanNotParseMessageException: 
	at org.kapott.hbci.comm.Comm.pingpong(Comm.java:124)
	at org.kapott.hbci.manager.HBCIKernelImpl.rawDoIt(HBCIKernelImpl.java:348)
	at org.kapott.hbci.manager.HBCIKernelImpl.rawDoIt(HBCIKernelImpl.java:176)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.sendData(AbstractRawHBCIDialog.java:123)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.execute(AbstractRawHBCIDialog.java:96)
	at org.kapott.hbci.manager.HBCIDialog.doDialogInit(HBCIDialog.java:116)
	at org.kapott.hbci.manager.HBCIDialog.doIt(HBCIDialog.java:445)
	at org.kapott.hbci.manager.HBCIHandler.execute(HBCIHandler.java:416)
	at de.willuhn.jameica.hbci.synchronize.hbci.HBCISynchronizeBackend$HBCIJobGroup.executeJobs(HBCISynchronizeBackend.java:371)
	at de.willuhn.jameica.hbci.synchronize.hbci.HBCISynchronizeBackend$HBCIJobGroup.sync(HBCISynchronizeBackend.java:292)
	at de.willuhn.jameica.hbci.synchronize.AbstractSynchronizeBackend$Worker.run(AbstractSynchronizeBackend.java:407)
	at de.willuhn.jameica.gui.GUI$7.run(GUI.java:1081)
Caused by: org.kapott.hbci.exceptions.ParseErrorException: reststring in DialogInitRes.MsgHead: 
	at org.kapott.hbci.protocol.MultipleSyntaxElements.initData(MultipleSyntaxElements.java:476)
	at org.kapott.hbci.protocol.MultipleSyntaxElements.init(MultipleSyntaxElements.java:539)
	at org.kapott.hbci.protocol.MultipleSEGs.init(MultipleSEGs.java:76)
	at org.kapott.hbci.protocol.factory.MultipleSEGsFactory.createMultipleSEGs(MultipleSEGsFactory.java:61)
	at org.kapott.hbci.protocol.MSG.parseNewChildContainer(MSG.java:187)
	at org.kapott.hbci.protocol.SyntaxElement.parseAndAppendNewChildContainer(SyntaxElement.java:457)
	at org.kapott.hbci.protocol.SyntaxElement.initData(SyntaxElement.java:388)
	at org.kapott.hbci.protocol.SyntaxElement.init(SyntaxElement.java:452)
	at org.kapott.hbci.protocol.MSG.init(MSG.java:171)
	at org.kapott.hbci.protocol.factory.MSGFactory.createMSG(MSGFactory.java:92)
	at org.kapott.hbci.protocol.factory.MSGFactory.createMSG(MSGFactory.java:78)
	at org.kapott.hbci.protocol.factory.MSGFactory.createMSG(MSGFactory.java:73)
	at org.kapott.hbci.comm.Comm.pingpong(Comm.java:121)
	... 11 more
Caused by: org.kapott.hbci.exceptions.ParseErrorException: reststring in DialogInitRes.MsgHead.SegHead: 
	at org.kapott.hbci.protocol.MultipleSyntaxElements.initData(MultipleSyntaxElements.java:476)
	at org.kapott.hbci.protocol.MultipleSyntaxElements.init(MultipleSyntaxElements.java:539)
	at org.kapott.hbci.protocol.MultipleDEGs.init(MultipleDEGs.java:104)
	at org.kapott.hbci.protocol.factory.MultipleDEGsFactory.createMultipleDEGs(MultipleDEGsFactory.java:61)
	at org.kapott.hbci.protocol.SEG.parseNewChildContainer(SEG.java:140)
	at org.kapott.hbci.protocol.SyntaxElement.parseAndAppendNewChildContainer(SyntaxElement.java:457)
	at org.kapott.hbci.protocol.SyntaxElement.initData(SyntaxElement.java:388)
	at org.kapott.hbci.protocol.SyntaxElement.init(SyntaxElement.java:452)
	at org.kapott.hbci.protocol.SEG.init(SEG.java:159)
	at org.kapott.hbci.protocol.factory.SEGFactory.createSEG(SEGFactory.java:60)
	at org.kapott.hbci.protocol.MultipleSEGs.parseAndAppendNewElement(MultipleSEGs.java:82)
	at org.kapott.hbci.protocol.MultipleSyntaxElements.initData(MultipleSyntaxElements.java:396)
	... 23 more
Caused by: org.kapott.hbci.exceptions.ParseErrorException: reststring in DialogInitRes.MsgHead.SegHead.code: 
	at org.kapott.hbci.protocol.MultipleSyntaxElements.initData(MultipleSyntaxElements.java:476)
	at org.kapott.hbci.protocol.MultipleSyntaxElements.init(MultipleSyntaxElements.java:539)
	at org.kapott.hbci.protocol.MultipleDEs.init(MultipleDEs.java:146)
	at org.kapott.hbci.protocol.factory.MultipleDEsFactory.createMultipleDEs(MultipleDEsFactory.java:61)
	at org.kapott.hbci.protocol.DEG.parseNewChildContainer(DEG.java:110)
	at org.kapott.hbci.protocol.SyntaxElement.parseAndAppendNewChildContainer(SyntaxElement.java:457)
	at org.kapott.hbci.protocol.SyntaxElement.initData(SyntaxElement.java:388)
	at org.kapott.hbci.protocol.SyntaxElement.init(SyntaxElement.java:452)
	at org.kapott.hbci.protocol.DEG.init(DEG.java:127)
	at org.kapott.hbci.protocol.factory.DEGFactory.createDEG(DEGFactory.java:60)
	at org.kapott.hbci.protocol.MultipleDEGs.parseAndAppendNewElement(MultipleDEGs.java:87)
	at org.kapott.hbci.protocol.MultipleSyntaxElements.initData(MultipleSyntaxElements.java:396)
	... 34 more
Caused by: org.kapott.hbci.exceptions.ParseErrorException: Fehler beim Erzeugen eines Syntax-DEs für DialogInitRes.MsgHead.SegHead.code
	at org.kapott.hbci.datatypes.factory.SyntaxDEFactory.createSyntaxDE(SyntaxDEFactory.java:166)
	at org.kapott.hbci.protocol.DE.parseValue(DE.java:222)
	at org.kapott.hbci.protocol.DE.initData(DE.java:279)
	at org.kapott.hbci.protocol.DE.init(DE.java:296)
	at org.kapott.hbci.protocol.factory.DEFactory.createDE(DEFactory.java:61)
	at org.kapott.hbci.protocol.MultipleDEs.parseAndAppendNewElement(MultipleDEs.java:128)
	at org.kapott.hbci.protocol.MultipleSyntaxElements.initData(MultipleSyntaxElements.java:396)
	... 45 more
[09.03.2021 12:11:09] *****************************************************
```

**Comment by willuhn** [comment]
Kannst du da mal mehrere HBCI-Versionen testen? Ich kann jetzt nicht sehen, welche du verwendet hast. Aber probiere auf jeden Fall mal HBCI 2.2 und FinTS3.

**Comment by thimo-seitz** [comment]
Eingestellt ist FinTS 3.0

**Comment by willuhn** [comment]
Dann teste mal bitte auch HBCI 2.2. FinTS3 enthält die ganzen PSD2-bedingten Änderungen, die bei Schlüsseldatei nicht zur Geltung kommen.

**Comment by thimo-seitz** [comment]
Bei HBCI 2.2:

```
[09.03.2021 12:21:32] Synchronisierung via FinTS/HBCI läuft
[09.03.2021 12:21:32]  
[09.03.2021 12:21:32] Synchronisiere Konto: Kontokorrent, IBAN DEXXXX [Commerzbank...sdner Bank]
[09.03.2021 12:21:32] Initialisiere Bank-Zugang
[09.03.2021 12:21:32]     Aktualisiere Bankparameter (BPD)
[09.03.2021 12:21:32]     Warte auf Antwortdaten
[09.03.2021 12:21:32] Aktualisiere BPD
[09.03.2021 12:21:32]   Kennung 1 - BPD-Parameter neu: 21, geändert: 0, gelöscht: 65
[09.03.2021 12:21:32]     Warte auf Antwortdaten
[09.03.2021 12:21:32] Fehler beim Öffnen des Schlüssels: Fehler beim Erzeugen eines HBCIHandler Objektes
```

**Comment by willuhn** [comment]
Bitte poste mal das gesamte Protokoll aus der jameica.log - siehe https://www.willuhn.de/wiki/doku.php?id=support:fehlermelden

**Comment by thimo-seitz** [comment]
Bei 2.2 beim synchronisieren kommt auch `angeforderter Sicherheitsmechanismus wird von der Bank nicht unterstützt`

**Comment by willuhn** [comment]
Ah! Dann hat die Bank dein Schlüsselprofil auf RAH umgestellt. Das wird von HBCI4Java leider nicht unterstützt. Siehe der Hinweis unter https://www.willuhn.de/wiki/doku.php?id=support:list:banken:misc:rdh#commerzbank sowie https://www.willuhn.de/wiki/doku.php?id=psd2#schluesseldatei

Da kann ich leider nicht weiterhelfen. Ich hatte mich am RAH-Support versucht, hatte es aber nicht hingekriegt. Trotz Demo-Konto.

**Comment by thimo-seitz** [comment]
Ah ok. Schade. Aber danke.
