### ISSUE TITLE
Fehler bei Comdirect photoTan

### ISSUE THREAD

**Issue by mtotschnig** [hbci4j/hbci4java#88]
Bei der Verbindung mit ComDirect läuft meine Implementierung zur Zeit in folgendes Problem:
Wenn der FinTS-Server zur TAN-Eingabe mittels photoTan auffordert:
```
2023-12-21 23:18:05,096 INFO [DefaultDispatcher-worker-3] HNHBK:1:3+000000004288+300+enXhduwyjowBAABrqDz2DBH2CgQA+1+enXhduwyjowBAABrqDz2DBH2CgQA:1'HNSHK:2:4+PIN:2+902+452635949+
1+1+2::A2HhduwyjowBAABrqDz2DBH2CgQA+1+1:20231221:231801+1:999:1+6:10:16+280:20041144:55315702:S:0:0'HIRMG:3:2+0010::Nachricht entgegengenommen.'HIRMS:4:2:5+0030::TAN-Eingabe erf
orderlich.'HITAN:5:6:5+4++40611985+Siehe Grafik+@3759@^@        image/png^N¢<U+0089>PNG
```
erhalte ich auch den Callback NEED_PT_PHOTOTAN, und meine Implementierung reagiert auch mit der Anzeige des Bildes, aber kurz darauf läuft der HBCI-Handler in folgende Exception:
```
2023-12-21 23:18:05,581 INFO [DefaultDispatcher-worker-3] org.kapott.hbci.exceptions.HBCI_Exception: *** error while signing
        at org.kapott.hbci.security.Sig.signIt(Sig.java:637)
        at ri.g.b(HBCIKernelImpl.java:28)
        at ri.g.c(HBCIKernelImpl.java:17)
        at org.kapott.hbci.dialog.a.g(AbstractRawHBCIDialog.java:7)
        at org.kapott.hbci.dialog.a.d(AbstractRawHBCIDialog.java:156)
        at ri.j.e(HBCIUser.java:585)
        at ri.e.i(HBCIHandler.java:16)
        at ri.e.<init>(HBCIHandler.java:56)
        at org.totschnig.fints.BankingViewModel.z(BankingViewModel.kt:283)
        at org.totschnig.fints.BankingViewModel$addBank$2.p(BankingViewModel.kt:44)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.m(ContinuationImpl.kt:9)
        at kotlinx.coroutines.o0.run(DispatchedTask.kt:111)
        at kotlinx.coroutines.internal.j$a.run(LimitedDispatcher.kt:4)
        at bc.i.run(Tasks.kt:3)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$b.run(CoroutineScheduler.kt:98)
Caused by: org.kapott.hbci.exceptions.InitializingException: error while initializing element DialogInitSCA.SigTail.UserSig.tan
        at org.kapott.hbci.datatypes.factory.SyntaxDEFactory.createSyntaxDE(SyntaxDEFactory.java:17)
        at vi.a.s(DE.java:119)
        at vi.h.i(MultipleSyntaxElements.java:141)
        at vi.k.s(SyntaxElement.java:70)
        at vi.h.i(MultipleSyntaxElements.java:141)
        at vi.k.s(SyntaxElement.java:70)
        at vi.h.i(MultipleSyntaxElements.java:141)
        at vi.k.s(SyntaxElement.java:70)
        at org.kapott.hbci.security.Sig.signIt(Sig.java:554)
        ... 14 more
Caused by: org.kapott.hbci.exceptions.InvalidArgumentException: length of image/png^N¢<U+0089>PNG ... (3757) not in range (1,99)
        at org.kapott.hbci.datatypes.SyntaxDE.setContent(SyntaxDE.java:60)
        at org.kapott.hbci.datatypes.SyntaxDE.initData(SyntaxDE.java:2)
        at org.kapott.hbci.datatypes.SyntaxDE.init(SyntaxDE.java:1)
        at org.kapott.hbci.datatypes.SyntaxAN.init(SyntaxAN.java:1)
        at org.kapott.hbci.datatypes.factory.SyntaxDEFactory.createSyntaxDE(SyntaxDEFactory.java:14)
        ... 22 more

```
Wobei die Fehlermeldung dort wo ich ... gesetzt habe, scheinbar die Daten der PNG-Datei enhält. Die Stacktrace ist leider von R8 obfuskiert, und ich kann das leider im Augenblick nicht ohne R8 reproduzieren, weil das auf dem Gerät eines Users passiert. Ich kann aber versuchen, die Stacktrace zu retracen, aber vielleicht springt das jemanden auch so ins Auge, was ich hier falsch mache?

**Comment by willuhn** [comment]
Du hast in dem Stringbuffer, der vom Callback übergeben wird, vermutlich nur deine TAN angehängt, die dort enthaltene PNG-Grafik aber vorher nicht entfernt. HBCI4Java versucht daher, die gesmate Grafik (incl. der angehängten TAN) als TAN in die Antwort-Nachricht einzufügen.

**Comment by mtotschnig** [comment]
@willuhn Vielen Dank, das wars.
